---
title: "R Cookbook"
author: "Carsten"
date: "06/07/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Cookbook}

#Deleting unnecessary columns
sc3data[, c("GWhs1"):=NULL]

#Copying a column from an other data table and insert it
sc3data <- cbind(sc3data, sc2data[,"GWhs4"])

#Building the sum of heat pump and hot water scaled numbers in a sepatrate variable
sc3data <- sc3data[, PumpandWater := GWh + GWhs4]

#Renaming PumpandWater to depict the right y in the colorbar
#setnames(sc3data, old=c("PumpandWater"), new=c("GWh")) #WARNING might not work properly
EcoVaHHDT <- copy(Mergedsc0DT)#Works

#Change the order in facet_grid()
sc3data$season <- factor(sc3data$season, levels = c("Spring","Summer",
                                                    "Autumn", "Winter"))

#
PricesDT[, .(n = .N), keyby = .(month = lubridate::month(dateTimeStart), dstFlag)]







testlabel <- c("00:00", "03:00", "09:00", "12:00", "15:00", "18:00", "21:00")

  scale_x_discrete(labels=testlabel)
  
  
  
  
  
  



sc1data$season <- factor(sc1data$season, levels = c("Spring","Summer",
                                                    "Autumn", "Winter"))



scale_x_time(breaks = c(hms::as.hms("00:00:00"), hms::as.hms("04:00:00"), hms::as.hms("08:00:00"),       hms::as.hms("12:00:00"), hms::as.hms("16:00:00"), 
  hms::as.hms("20:00:00"))) 



scale_color_discrete(breaks=c("Off Peak 1", "Morning Peak", "Off Peak 2",
                                "Evening Peak")) +



theme(text = element_text(family = "Cambria")) +

setnames(sc1data, old=c("GWh"), new=c("MWh"))










```
