<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Ben Anderson (b.anderson@soton.ac.uk, @dataknut)" />


<title>Processing, cleaning and saving NZ GREEN Grid project 1 minute electricity power data</title>

<script src="processGridSpy1minData_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="processGridSpy1minData_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="processGridSpy1minData_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="processGridSpy1minData_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="processGridSpy1minData_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="processGridSpy1minData_files/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="processGridSpy1minData_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="processGridSpy1minData_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="processGridSpy1minData_files/navigation-1.1/tabsets.js"></script>
<script src="processGridSpy1minData_files/navigation-1.1/codefolding.js"></script>
<link href="processGridSpy1minData_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="processGridSpy1minData_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>




<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>

<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Processing, cleaning and saving NZ GREEN Grid project 1 minute electricity power data</h1>
<h4 class="author"><em>Ben Anderson (<a href="mailto:b.anderson@soton.ac.uk">b.anderson@soton.ac.uk</a>, <code>@dataknut</code>)</em></h4>
<h4 class="date"><em>Last run at: 2018-06-05 13:02:02</em></h4>

</div>



<div id="status" class="section level1">
<h1><span class="header-section-number">1</span> Status</h1>
<p>Full run using all data from /Volumes/hum-csafe/Research Projects/GREEN Grid/_RAW DATA/GridSpyData/</p>
<p>refreshData = 0 so re-using previous output. Should be relatively quick.</p>
</div>
<div id="citation" class="section level1">
<h1><span class="header-section-number">2</span> Citation</h1>
<p>If you wish to use any of the material from this report please cite as:</p>
<ul>
<li>Anderson, B. (2018) Processing, cleaning and saving NZ GREEN Grid project 1 minute electricity power data, University of Otago: Dunedin, NZ.</li>
</ul>

</div>
<div id="introduction" class="section level1">
<h1><span class="header-section-number">3</span> Introduction</h1>
<p>Report circulation:</p>
<ul>
<li>Restricted to: <a href="https://www.otago.ac.nz/centre-sustainability/research/energy/otago050285.html">NZ GREEN Grid</a> project partners and contractors.</li>
</ul>
<div id="purpose" class="section level2">
<h2><span class="header-section-number">3.1</span> Purpose</h2>
<p>This report is intended to:</p>
<ul>
<li>load and clean the project electricity power data (Grid Spy)</li>
<li>save the cleaned data out as a single file per household</li>
<li>produce summary data quality statistics</li>
</ul>
<p>The resulting cleaned data has <em>no</em> identifying information such as names, addresses, email addresses, telephone numbers and is therefore safe to share across all partners.</p>
<p>The data contains a unique household id which can be used to link it to the NZ GREEN Grid time use diaries and dwelling/appliance surveys. With some additional non-disclosure checks it should also be safe to archive all of these linkable datasets for re-use via the UK <a href="http://reshare.ukdataservice.ac.uk/">reshare</a> service.</p>
</div>
<div id="requirements" class="section level2">
<h2><span class="header-section-number">3.2</span> Requirements:</h2>
<ul>
<li>grid spy 1 minute data downloads</li>
</ul>
</div>
<div id="history" class="section level2">
<h2><span class="header-section-number">3.3</span> History</h2>
<p>Generally tracked via our git.soton <a href="https://git.soton.ac.uk/ba1e12/nzGREENGrid">repo</a>:</p>
<ul>
<li><a href="https://git.soton.ac.uk/ba1e12/nzGREENGrid/commits/master">history</a></li>
<li><a href="https://git.soton.ac.uk/ba1e12/nzGREENGrid/issues">issues</a></li>
</ul>
</div>
<div id="support" class="section level2">
<h2><span class="header-section-number">3.4</span> Support</h2>
<p>This work was supported by:</p>
<ul>
<li>The <a href="https://www.otago.ac.nz/">University of Otago</a></li>
<li>The New Zealand <a href="http://www.mbie.govt.nz/">Ministry of Business, Innovation and Employment (MBIE)</a></li>
<li><a href="http://www.energy.soton.ac.uk/tag/spatialec/">SPATIALEC</a> - a <a href="http://ec.europa.eu/research/mariecurieactions/about-msca/actions/if/index_en.htm">Marie Skłodowska-Curie Global Fellowship</a> based at the University of Otago’s <a href="http://www.otago.ac.nz/centre-sustainability/staff/otago673896.html">Centre for Sustainability</a> (2017-2019) &amp; the University of Southampton’s Sustainable Energy Research Group (2019-202).</li>
</ul>
<p>This work is (c) 2018 the University of Southampton.</p>
<p>We do not ‘support’ the code but if you have a problem check the <a href="https://git.soton.ac.uk/ba1e12/nzGREENGrid/issues">issues</a> on our <a href="https://git.soton.ac.uk/ba1e12/nzGREENGrid">repo</a> and if it doesn’t already exist, open one. We might be able to fix it :-)</p>
</div>
</div>
<div id="obtain-listing-of-files" class="section level1">
<h1><span class="header-section-number">4</span> Obtain listing of files</h1>
<p>In this section we generate a listing of all 1 minute data files that we have received. If we are running over the complete dataset then we will be using data from:</p>
<ul>
<li>/hum-csafe/Research Projects/GREEN Grid/_RAW DATA/GridSpyData/</li>
</ul>
<p>In this run we are using data from:</p>
<ul>
<li>/Volumes/hum-csafe/Research Projects/GREEN Grid/_RAW DATA/GridSpyData/</li>
</ul>
<p>If these do not match then this may be a test run.</p>
<pre><code>## [1] &quot;Re-using filelist&quot;</code></pre>
<pre><code>## [1] &quot;Overall we have 22376 files from 44 households.&quot;</code></pre>
<p>Overall we have 22,376 files from 44 households. Of the 22,376, 13,080 (58.46%) were <em>not</em> loaded/checked as their file sizes indicated that they contained no data.</p>
<div id="date-format-checks" class="section level2">
<h2><span class="header-section-number">4.1</span> Date format checks</h2>
<p>We now need to check how many of the loaded files have an ambiguous or default date - these could introduce errors.</p>
<table>
<caption>Number of files and min/max date (as char) with given date column names by inferred date format</caption>
<thead>
<tr class="header">
<th align="left">dateColName</th>
<th align="left">dateFormat</th>
<th align="right">nFiles</th>
<th align="left">minDate</th>
<th align="left">maxDate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">date NZ</td>
<td align="left">dmy - definite</td>
<td align="right">1</td>
<td align="left">27/03/2015</td>
<td align="left">27/03/2015</td>
</tr>
<tr class="even">
<td align="left">date NZ</td>
<td align="left">mdy - definite</td>
<td align="right">2</td>
<td align="left">5/26/2016</td>
<td align="left">5/26/2016</td>
</tr>
<tr class="odd">
<td align="left">date NZ</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
<td align="right">12</td>
<td align="left">2014-01-06</td>
<td align="left">2016-06-07</td>
</tr>
<tr class="even">
<td align="left">date NZ</td>
<td align="left">ymd - definite</td>
<td align="right">67</td>
<td align="left">2014-05-24</td>
<td align="left">2016-07-13</td>
</tr>
<tr class="odd">
<td align="left">date UTC</td>
<td align="left">ambiguous</td>
<td align="right">28</td>
<td align="left">11-10-16</td>
<td align="left">27/07/14</td>
</tr>
<tr class="even">
<td align="left">date UTC</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
<td align="right">3607</td>
<td align="left">2014-11-03</td>
<td align="left">2018-05-12</td>
</tr>
<tr class="odd">
<td align="left">date UTC</td>
<td align="left">ymd - definite</td>
<td align="right">5579</td>
<td align="left">2015-03-26</td>
<td align="left">2018-05-28</td>
</tr>
<tr class="even">
<td align="left">unknown - do not load (fsize = 2751)</td>
<td align="left">NA</td>
<td align="right">1812</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">unknown - do not load (fsize = 43)</td>
<td align="left">NA</td>
<td align="right">11268</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
<p>Results to note:</p>
<ul>
<li>There are 28 ambiguous files</li>
<li>The non-loaded files only have 2 distinct file sizes, confirming that they are unlikely to contain useful data.</li>
</ul>
<p>We now inspect the ambiguous and (some of) the default files.</p>
<p>To help with data cleaning the following table lists files that have ambiguous dates.</p>
<pre class="r"><code># list ambigious files
aList &lt;- fListCompleteDT[dateFormat == &quot;ambiguous&quot;, 
                         .(file, dateColName, dateExample, dateFormat)]

cap &lt;- paste0(&quot;All &quot;, nrow(aList), 
              &quot; files with an ambiguous dateFormat&quot;)

knitr::kable(caption = cap, aList)</code></pre>
<table>
<caption>All 28 files with an ambiguous dateFormat</caption>
<thead>
<tr class="header">
<th align="left">file</th>
<th align="left">dateColName</th>
<th align="left">dateExample</th>
<th align="left">dateFormat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">rf_06/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_07/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_08/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_10/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_11/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_13/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_19/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_21/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_22/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_23/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_24/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">27/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_25/12Oct2016-20Nov2017at1.csv</td>
<td align="left">date UTC</td>
<td align="left">11-10-16</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_26/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_27/15Jul2014-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">27/07/14</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_29/24Mar2015-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">25/03/15</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_30/15Feb2016-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">14/02/16</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_30/24Mar2015-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">27/03/15</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_31/24Mar2015-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">25/03/15</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_34/18Jan2016-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">17/01/16</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_34/20Jul2015-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">19/07/15</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_34/24Mar2015-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">26/03/15</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_35/24Mar2015-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">23/03/15</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_39/24Mar2015-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">27/03/15</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_43/24Mar2015-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">26/03/15</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_43/27Mar2015-18Oct2015at1.csv</td>
<td align="left">date UTC</td>
<td align="left">26/03/15</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_44/24Mar2015-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">24/03/15</td>
<td align="left">ambiguous</td>
</tr>
<tr class="odd">
<td align="left">rf_46/12Oct2016-20Nov2017at1.csv</td>
<td align="left">date UTC</td>
<td align="left">11-10-16</td>
<td align="left">ambiguous</td>
</tr>
<tr class="even">
<td align="left">rf_47/24Mar2015-25May2016at1.csv</td>
<td align="left">date UTC</td>
<td align="left">24/03/15</td>
<td align="left">ambiguous</td>
</tr>
</tbody>
</table>
<p>Check against file names to see what is reasonable and then fix them.</p>
<pre class="r"><code>fListCompleteDT &lt;- nzGREENGrid::fixAmbiguousDates(fListCompleteDT)</code></pre>
<pre><code>## [1] &quot;Fixed 28 files with an ambiguous dateFormat&quot;</code></pre>
<p>The following table lists up to 10 of the ‘date NZ’ files which are set by default - do they look OK to assume the default dateFormat? Compare the file names with the dateExample…</p>
<pre class="r"><code># list default files with NZ time
aList &lt;- fListCompleteDT[dateColName == &quot;date NZ&quot; &amp; dateFormat %like% &quot;default&quot;, 
                         .(file, fSize, dateColName, dateExample, dateFormat)]

cap &lt;- paste0(&quot;First 10 (max) of &quot;, nrow(aList), 
              &quot; files with dateColName = &#39;date NZ&#39; and default dateFormat&quot;)

knitr::kable(caption = cap, head(aList))</code></pre>
<table>
<caption>First 10 (max) of 12 files with dateColName = ‘date NZ’ and default dateFormat</caption>
<thead>
<tr class="header">
<th align="left">file</th>
<th align="right">fSize</th>
<th align="left">dateColName</th>
<th align="left">dateExample</th>
<th align="left">dateFormat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">rf_01/1Jan2014-24May2014at1.csv</td>
<td align="right">6255737</td>
<td align="left">date NZ</td>
<td align="left">2014-01-06</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="even">
<td align="left">rf_02/1Jan2014-24May2014at1.csv</td>
<td align="right">6131625</td>
<td align="left">date NZ</td>
<td align="left">2014-03-03</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="odd">
<td align="left">rf_06/24May2014-24May2015at1.csv</td>
<td align="right">19398444</td>
<td align="left">date NZ</td>
<td align="left">2014-06-09</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="even">
<td align="left">rf_10/24May2014-24May2015at1.csv</td>
<td align="right">24386048</td>
<td align="left">date NZ</td>
<td align="left">2014-07-09</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="odd">
<td align="left">rf_11/24May2014-24May2015at1.csv</td>
<td align="right">23693893</td>
<td align="left">date NZ</td>
<td align="left">2014-07-08</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="even">
<td align="left">rf_12/24May2014-24May2015at1.csv</td>
<td align="right">21191785</td>
<td align="left">date NZ</td>
<td align="left">2014-07-09</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
</tbody>
</table>
<p>The following table lists up to 10 of the ‘date UTC’ files which are set by default - do they look OK to assume the default dateFormat? Compare the file names with the dateExample…</p>
<pre class="r"><code># list default files with UTC time
aList &lt;- fListCompleteDT[dateColName == &quot;date UTC&quot; &amp; dateFormat %like% &quot;default&quot;, 
                         .(file, fSize, dateColName, dateExample, dateFormat)]

cap &lt;- paste0(&quot;First 10 (max) of &quot;, nrow(aList), 
              &quot; files with dateColName = &#39;date UTC&#39; and default dateFormat&quot;)

knitr::kable(caption = cap, head(aList, 10))</code></pre>
<table>
<caption>First 10 (max) of 3607 files with dateColName = ‘date UTC’ and default dateFormat</caption>
<thead>
<tr class="header">
<th align="left">file</th>
<th align="right">fSize</th>
<th align="left">dateColName</th>
<th align="left">dateExample</th>
<th align="left">dateFormat</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">rf_06/10Apr2018-11Apr2018at1.csv</td>
<td align="right">156944</td>
<td align="left">date UTC</td>
<td align="left">2018-04-09</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="even">
<td align="left">rf_06/10Dec2017-11Dec2017at1.csv</td>
<td align="right">156601</td>
<td align="left">date UTC</td>
<td align="left">2017-12-09</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="odd">
<td align="left">rf_06/10Feb2018-11Feb2018at1.csv</td>
<td align="right">153353</td>
<td align="left">date UTC</td>
<td align="left">2018-02-09</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="even">
<td align="left">rf_06/10Jan2018-11Jan2018at1.csv</td>
<td align="right">153982</td>
<td align="left">date UTC</td>
<td align="left">2018-01-09</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="odd">
<td align="left">rf_06/10Mar2018-11Mar2018at1.csv</td>
<td align="right">156471</td>
<td align="left">date UTC</td>
<td align="left">2018-03-09</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="even">
<td align="left">rf_06/10May2018-11May2018at1.csv</td>
<td align="right">156683</td>
<td align="left">date UTC</td>
<td align="left">2018-05-09</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="odd">
<td align="left">rf_06/10Nov2017-11Nov2017at1.csv</td>
<td align="right">155639</td>
<td align="left">date UTC</td>
<td align="left">2017-11-09</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="even">
<td align="left">rf_06/11Apr2018-12Apr2018at1.csv</td>
<td align="right">157181</td>
<td align="left">date UTC</td>
<td align="left">2018-04-10</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="odd">
<td align="left">rf_06/11Dec2017-12Dec2017at1.csv</td>
<td align="right">157814</td>
<td align="left">date UTC</td>
<td align="left">2017-12-10</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
<tr class="even">
<td align="left">rf_06/11Feb2018-12Feb2018at1.csv</td>
<td align="right">153859</td>
<td align="left">date UTC</td>
<td align="left">2018-02-10</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
</tr>
</tbody>
</table>
<p>Check final date formats:</p>
<table>
<caption>Number of files &amp; min/max dates (as char) with given date column names by final imputed date format</caption>
<thead>
<tr class="header">
<th align="left">dateColName</th>
<th align="left">dateFormat</th>
<th align="right">nFiles</th>
<th align="left">minDate</th>
<th align="left">maxDate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">date NZ</td>
<td align="left">dmy - definite</td>
<td align="right">1</td>
<td align="left">27/03/2015</td>
<td align="left">27/03/2015</td>
</tr>
<tr class="even">
<td align="left">date NZ</td>
<td align="left">mdy - definite</td>
<td align="right">2</td>
<td align="left">5/26/2016</td>
<td align="left">5/26/2016</td>
</tr>
<tr class="odd">
<td align="left">date NZ</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
<td align="right">12</td>
<td align="left">2014-01-06</td>
<td align="left">2016-06-07</td>
</tr>
<tr class="even">
<td align="left">date NZ</td>
<td align="left">ymd - definite</td>
<td align="right">67</td>
<td align="left">2014-05-24</td>
<td align="left">2016-07-13</td>
</tr>
<tr class="odd">
<td align="left">date UTC</td>
<td align="left">dmy - inferred</td>
<td align="right">28</td>
<td align="left">11-10-16</td>
<td align="left">27/07/14</td>
</tr>
<tr class="even">
<td align="left">date UTC</td>
<td align="left">ymd - default (but day/month value &lt;= 12)</td>
<td align="right">3607</td>
<td align="left">2014-11-03</td>
<td align="left">2018-05-12</td>
</tr>
<tr class="odd">
<td align="left">date UTC</td>
<td align="left">ymd - definite</td>
<td align="right">5579</td>
<td align="left">2015-03-26</td>
<td align="left">2018-05-28</td>
</tr>
<tr class="even">
<td align="left">unknown - do not load (fsize = 2751)</td>
<td align="left">NA</td>
<td align="right">1812</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">unknown - do not load (fsize = 43)</td>
<td align="left">NA</td>
<td align="right">11268</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="data-file-quality-checks" class="section level2">
<h2><span class="header-section-number">4.2</span> Data file quality checks</h2>
<p>The following chart shows the distribution of these files over time using their sizes. Note that white indicates the presence of small files which may not contain observations.</p>
<p><img src="processGridSpy1minData_files/figure-html/allFileSizesPlot-1.png" /><!-- --></p>
<pre><code>## Saving 7 x 5 in image</code></pre>
<p>The following chart shows the same chart but only for files which we think contain data.</p>
<p><img src="processGridSpy1minData_files/figure-html/loadedFileSizesPlot-1.png" /><!-- --></p>
<pre><code>## Saving 7 x 5 in image</code></pre>
</div>
</div>
<div id="load-data-files" class="section level1">
<h1><span class="header-section-number">5</span> Load data files</h1>
<div id="grid-spy-metadata" class="section level2">
<h2><span class="header-section-number">5.1</span> Grid Spy metadata</h2>
<p>In this section we load metadata from /Users/ben/Syncplicity Folders/Green Grid Project Management Folder/Gridspy/Master list of Gridspy units.xlsx to link to the power data.</p>
<table>
<caption>Meta data for sample</caption>
<thead>
<tr class="header">
<th align="left">sample</th>
<th align="left">hhID</th>
<th align="left">Adults</th>
<th align="left">Teenagers</th>
<th align="left">Children</th>
<th align="left">removed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Unison</td>
<td align="left">rf_28</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">3(12,8,4)</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Unison</td>
<td align="left">rf_29</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">1 (7 months old)</td>
<td align="left">live</td>
</tr>
<tr class="odd">
<td align="left">Unison</td>
<td align="left">rf_30</td>
<td align="left">2</td>
<td align="left">0</td>
<td align="left">0</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Unison</td>
<td align="left">rf_31</td>
<td align="left">2 (Plus cousin)</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">live</td>
</tr>
<tr class="odd">
<td align="left">Unison</td>
<td align="left">rf_32</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">2 (7 and 4years old)</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Unison</td>
<td align="left">rf_33</td>
<td align="left">2</td>
<td align="left">1(14yold)</td>
<td align="left">1 (6yold)</td>
<td align="left">live</td>
</tr>
<tr class="odd">
<td align="left">Unison</td>
<td align="left">rf_34</td>
<td align="left">3</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Unison</td>
<td align="left">rf_35</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">42322</td>
</tr>
<tr class="odd">
<td align="left">Unison</td>
<td align="left">rf_36</td>
<td align="left">1</td>
<td align="left">2 (14 and 12)</td>
<td align="left">NA</td>
<td align="left">live</td>
</tr>
<tr class="even">
<td align="left">Unison</td>
<td align="left">rf_37</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">live</td>
</tr>
<tr class="odd">
<td align="left">Unison</td>
<td align="left">rf_38</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Unison</td>
<td align="left">rf_38</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">2 (&lt;12)</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Unison</td>
<td align="left">rf_39</td>
<td align="left">2</td>
<td align="left">1 (16 YO)</td>
<td align="left">NA</td>
<td align="left">live</td>
</tr>
<tr class="even">
<td align="left">Unison</td>
<td align="left">rf_40</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">42330</td>
</tr>
<tr class="odd">
<td align="left">Unison</td>
<td align="left">rf_41</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">2 (11 and 8)</td>
<td align="left">live</td>
</tr>
<tr class="even">
<td align="left">Unison</td>
<td align="left">rf_42</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">3 (&lt;12 yold, 1 10 YO)</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Unison</td>
<td align="left">rf_43</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">42296</td>
</tr>
<tr class="even">
<td align="left">Unison</td>
<td align="left">rf_44</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">2 (10 and 7)</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Unison</td>
<td align="left">rf_45</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">3 (&lt;12 years old)</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Unison</td>
<td align="left">rf_46</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">1 (4yold-50%)</td>
<td align="left">live</td>
</tr>
<tr class="odd">
<td align="left">Unison</td>
<td align="left">rf_47</td>
<td align="left">3</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_12</td>
<td align="left">1</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">3/6/1015</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_25</td>
<td align="left">1</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_23</td>
<td align="left">1</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_26</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_06</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_19</td>
<td align="left">1</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_10</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">1(3yo)</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_11</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_13</td>
<td align="left">2</td>
<td align="left">1(16yo)</td>
<td align="left">1(11)</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_09</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">1</td>
<td align="left">42171</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_07</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">2</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_22</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_08</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_18</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">1(1yo)</td>
<td align="left">42532</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_17_oldNo reused</td>
<td align="left">2</td>
<td align="left">1(13yo)</td>
<td align="left">1(11yo)</td>
<td align="left">42457</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_14</td>
<td align="left">1</td>
<td align="left">NA</td>
<td align="left">1 (11 yo)</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_16</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">42089</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_21</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">42821</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_20</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">2</td>
<td align="left">42166</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_27</td>
<td align="left">2</td>
<td align="left">1</td>
<td align="left">1</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_15_old</td>
<td align="left">1</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">42019</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_24</td>
<td align="left">2</td>
<td align="left">NA</td>
<td align="left">2</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">Powerco</td>
<td align="left">rf_15</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">42462</td>
</tr>
<tr class="odd">
<td align="left">Powerco</td>
<td align="left">rf_17 sn_662</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
</div>
<div id="grid-spy-data" class="section level2">
<h2><span class="header-section-number">5.2</span> Grid Spy data</h2>
<p>In this section we load the data files that have a file size &gt; 3000 bytes. Things to note:</p>
<ul>
<li>We assume that any files smaller than this value have no observations. This is based on:
<ul>
<li>Manual inspection of several small files</li>
<li>The identical (small) file sizes involved</li>
<li><em>But</em> we should probably test the first few lines to double check…</li>
</ul></li>
<li>We have to deal with quite a lot of duplication some of which has caused the different date formats. See our <a href="https://git.soton.ac.uk/ba1e12/nzGREENGrid/issues?scope=all&amp;utf8=%E2%9C%93&amp;state=all">repo issues list</a>.</li>
</ul>
<p>The following table shows the number of files per household that we will load.</p>
<pre class="r"><code># check files to load
t &lt;- fListCompleteDT[dateColName %like% &quot;do not load&quot;, .(nFiles = .N,
                       meanSize = mean(fSize),
                       minFileDate = min(fMDate),
                       maxFileDate = max(fMDate)), keyby = .(hhID)]

knitr::kable(caption = &quot;Summary of household files to load&quot;, t)</code></pre>
<table>
<caption>Summary of household files to load</caption>
<thead>
<tr class="header">
<th align="left">hhID</th>
<th align="right">nFiles</th>
<th align="right">meanSize</th>
<th align="left">minFileDate</th>
<th align="left">maxFileDate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">rf_01</td>
<td align="right">506</td>
<td align="right">1659.237</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_02</td>
<td align="right">506</td>
<td align="right">1659.237</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_06</td>
<td align="right">302</td>
<td align="right">2751.000</td>
<td align="left">2017-01-11</td>
<td align="left">2017-11-08</td>
</tr>
<tr class="even">
<td align="left">rf_07</td>
<td align="right">302</td>
<td align="right">2751.000</td>
<td align="left">2017-01-11</td>
<td align="left">2017-11-08</td>
</tr>
<tr class="odd">
<td align="left">rf_08</td>
<td align="right">505</td>
<td align="right">1662.438</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_09</td>
<td align="right">506</td>
<td align="right">1659.237</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_10</td>
<td align="right">152</td>
<td align="right">43.000</td>
<td align="left">2017-11-03</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_12</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_13</td>
<td align="right">68</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2017-03-18</td>
</tr>
<tr class="even">
<td align="left">rf_14</td>
<td align="right">180</td>
<td align="right">43.000</td>
<td align="left">2017-05-04</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_15</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_16</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_17</td>
<td align="right">296</td>
<td align="right">43.000</td>
<td align="left">2017-01-18</td>
<td align="left">2018-05-28</td>
</tr>
<tr class="even">
<td align="left">rf_18</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_20</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_21</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_22</td>
<td align="right">139</td>
<td align="right">43.000</td>
<td align="left">2017-05-01</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_25</td>
<td align="right">505</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_26</td>
<td align="right">94</td>
<td align="right">43.000</td>
<td align="left">2017-08-21</td>
<td align="left">2017-12-17</td>
</tr>
<tr class="even">
<td align="left">rf_27</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_28</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_29</td>
<td align="right">3</td>
<td align="right">43.000</td>
<td align="left">2017-01-25</td>
<td align="left">2017-01-27</td>
</tr>
<tr class="odd">
<td align="left">rf_30</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_32</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_34</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_35</td>
<td align="right">376</td>
<td align="right">43.000</td>
<td align="left">2017-05-19</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_36</td>
<td align="right">49</td>
<td align="right">43.000</td>
<td align="left">2017-12-06</td>
<td align="left">2018-04-26</td>
</tr>
<tr class="even">
<td align="left">rf_38</td>
<td align="right">308</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_39</td>
<td align="right">124</td>
<td align="right">43.000</td>
<td align="left">2017-05-14</td>
<td align="left">2018-03-20</td>
</tr>
<tr class="even">
<td align="left">rf_40</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_41</td>
<td align="right">8</td>
<td align="right">43.000</td>
<td align="left">2017-09-19</td>
<td align="left">2018-04-27</td>
</tr>
<tr class="even">
<td align="left">rf_42</td>
<td align="right">464</td>
<td align="right">43.000</td>
<td align="left">2017-02-20</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_43</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_45</td>
<td align="right">505</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_46</td>
<td align="right">98</td>
<td align="right">43.000</td>
<td align="left">2018-02-22</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_47</td>
<td align="right">506</td>
<td align="right">43.000</td>
<td align="left">2017-01-11</td>
<td align="left">2018-05-30</td>
</tr>
</tbody>
</table>
<p>Now load, clean and save the valid data giving feedback where appropriate.</p>
<pre class="r"><code># process the data &amp; update the fListCompleteDT
# get a few rows of data as an example
# refresh the data depending on refreshData (set in ./setup.R)

if(refreshData){
  print(paste0(&quot;&#39;refreshData&#39; = &quot;, refreshData, &quot; so re-building filelist&quot;))
  # returns the updated file list into fListCompleteDT
  # creates hhStatDT (used below)
  # puts top 6 rows of last file into lastOfHeadDT
  fListCompleteDT &lt;- nzGREENGrid::processGridSpyDataFiles(fListCompleteDT, fListFinal)
} else {
  print(paste0(&quot;&#39;refreshData&#39; = &quot;, refreshData, &quot; so re-using filelist&quot;))
  fListCompleteDT &lt;- fread(paste0(outPath,fListFinal))
  
  # need to create hhStatDT
  ofile &lt;- paste0(outPath, &quot;hhDailyObservationsStats.csv&quot;)
  hhStatDT &lt;- fread(ofile)
  
  # need to get lastOfHeadDT
  # do this by getting the first in the processed list
  dPath &lt;- paste0(outPath,&quot;data/&quot;)
  fList &lt;- list.files(path = dPath, pattern = &quot;csv.gz&quot;)
  print(paste0(&quot;Re-using saved data file...&quot;))
  lastOfHeadDT &lt;- head(read_csv(paste0(dPath, fList[1])))
}</code></pre>
<pre><code>## [1] &quot;&#39;refreshData&#39; = 0 so re-using filelist&quot;
## [1] &quot;Re-using saved data file...&quot;</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   hhID = col_character(),
##   r_dateTime = col_datetime(format = &quot;&quot;),
##   circuit = col_character(),
##   powerW = col_double()
## )</code></pre>
<pre class="r"><code># test
kable(caption = &quot;Example data rows&quot;, lastOfHeadDT)</code></pre>
<table>
<caption>Example data rows</caption>
<thead>
<tr class="header">
<th align="left">hhID</th>
<th align="left">r_dateTime</th>
<th align="left">circuit</th>
<th align="right">powerW</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">rf_01</td>
<td align="left">2014-01-06 03:03:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">45.58</td>
</tr>
<tr class="even">
<td align="left">rf_01</td>
<td align="left">2014-01-06 03:04:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">45.58</td>
</tr>
<tr class="odd">
<td align="left">rf_01</td>
<td align="left">2014-03-07 02:56:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">45.58</td>
</tr>
<tr class="even">
<td align="left">rf_01</td>
<td align="left">2014-03-07 02:57:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">54.13</td>
</tr>
<tr class="odd">
<td align="left">rf_01</td>
<td align="left">2014-03-07 02:58:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">136.26</td>
</tr>
<tr class="even">
<td align="left">rf_01</td>
<td align="left">2014-03-07 02:59:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">141.96</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="data-quality-analysis" class="section level1">
<h1><span class="header-section-number">6</span> Data quality analysis</h1>
<p>Now produce some data quality plots &amp; tables.</p>
<div id="circuit-label-checks" class="section level2">
<h2><span class="header-section-number">6.1</span> Circuit label checks</h2>
<p>The following table shows the number of data files with different circuit labels by household. In theory there should only be one unique list per household and it should be present in every data file. If this is not the case then this implies that:</p>
<ul>
<li>some of the circuit labels for these households may have been changed during the data collection process;</li>
<li>some of the circuit labels may have character conversion errors which have changed the labels during the data collection process;</li>
<li>at least one file from one household has been saved to a folder containing data from a different household (unfortunately the raw data files do <em>not</em> contain household IDs in the data or the file names which would enable checking/preventative filtering). This will be visible in the table if two households appear to share <em>exactly</em> the same list of circuit labels.</li>
</ul>
<p>Some or all of these may be true at any given time!</p>
<blockquote>
<p>NB: This table is only legible in the html version of this report because latex does a very bad job of wrapping table cell text. A version is saved in /Volumes/hum-csafe/Research Projects/GREEN Grid/Clean_data/safe/gridSpy/1min/circuitLabelCheck.csv for viewing in e.g. xl.</p>
</blockquote>
<table>
<caption>Circuit labels list by household</caption>
<thead>
<tr class="header">
<th></th>
<th align="right">rf_06</th>
<th align="right">rf_07</th>
<th align="right">rf_08</th>
<th align="right">rf_09</th>
<th align="right">rf_10</th>
<th align="right">rf_11</th>
<th align="right">rf_12</th>
<th align="right">rf_13</th>
<th align="right">rf_14</th>
<th align="right">rf_15</th>
<th align="right">rf_15_old</th>
<th align="right">rf_16</th>
<th align="right">rf_17 sn_662</th>
<th align="right">rf_17_oldNo reused</th>
<th align="right">rf_18</th>
<th align="right">rf_19</th>
<th align="right">rf_20</th>
<th align="right">rf_21</th>
<th align="right">rf_22</th>
<th align="right">rf_23</th>
<th align="right">rf_24</th>
<th align="right">rf_25</th>
<th align="right">rf_26</th>
<th align="right">rf_27</th>
<th align="right">rf_28</th>
<th align="right">rf_29</th>
<th align="right">rf_30</th>
<th align="right">rf_31</th>
<th align="right">rf_32</th>
<th align="right">rf_33</th>
<th align="right">rf_34</th>
<th align="right">rf_35</th>
<th align="right">rf_36</th>
<th align="right">rf_37</th>
<th align="right">rf_38</th>
<th align="right">rf_39</th>
<th align="right">rf_40</th>
<th align="right">rf_41</th>
<th align="right">rf_42</th>
<th align="right">rf_43</th>
<th align="right">rf_44</th>
<th align="right">rf_45</th>
<th align="right">rf_46</th>
<th align="right">rf_47</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bed 2, 2nd Fridge$2828, Heat Pump$2826, Hot Water - Controlled$2825, Incomer - Uncontrolled$2824, Kitchen, Laundry &amp; Beds 1&amp;3$2829, Oven &amp; Oven Wall Appliances$2827</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Bedroom &amp; Lounge Heat Pumps$2741, Incomer 1 - All$2738, Incomer 2 - All$2737, Kitchen Appliances$2735, Laundry$2734, Oven$2736, PV 1$2739, PV 2$2733, Theatre Heat Pump$2740</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">508</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Bedrooms &amp; Lounge$2602, Heat Pump$2598, Incomer - All$2599, Kitchen Appliances$2601, Laundry &amp; Garage$2597, Oven$2600</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">358</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Downstairs (inc 1 Heat Pump)$2212, Hot Water - Controlled$2208, Incomer - Uncontrolled$2209, Kitchen &amp; Laundry$2213, Oven &amp; Hob$2210, Upstairs Heat Pumps$2211</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">440</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Fridge$2752, Heat Pump &amp; Washing Machine$2750, Incomer - All$2748, Kitchen Appliances &amp; Garage$2753, Lower Bedrooms &amp; Bathrooms$2751, Oven$2749</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Hallway &amp; Washing Machine$2683, Hot Water - Controlled$2679, Incomer 1 - Uncont inc Oven$2681, Incomer 2 - Uncont inc Stove$2680, Kitchen Appliances &amp; Bedrooms$2684, Microwave &amp; Breadmaker$2682</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Heat Pump (x2) &amp; Lounge Power$4166, Hot Water - Controlled$4167, Incomer - Uncontrolled$4168, Kitchen Appliances$4163, Laundry$4164, Lighting$4165</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Heat Pump &amp; 2 x Bathroom Heat$4171, Incomer - All$4170, Kitchen Power &amp; Heat, Lounge$4174, Laundry, Garage &amp; 2 Bedrooms$4173, Lighting$4172, Wall Oven$4169</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">3</td>
</tr>
<tr class="odd">
<td>Heat Pump &amp; Bedroom 2$2731, Incomer 1 - Uncont - Inc Hob$2729, Incomer 2 - Uncont - Inc Oven$2730, Kitchen Appliances$2727, Laundry$2732, Lounge, Dining &amp; Bedrooms$2728</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Heat Pump &amp; Kitchen Appliances$4186, Hot Water - Controlled$4184, Incomer - Uncontrolled$4181, Laundry$4185, Lighting$4183, Oven$4182</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">505</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Heat Pump &amp; Lounge$2590, Hob$2589, Hot Water Cpbd Heater- Cont$2586, Incomer - Uncontrolled$2585, Kitchen Appliances &amp; Laundry$2588, Spa - Uncontrolled$2587</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">508</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Heat Pump &amp; Misc$2107, Hob$2109, Hot Water - Controlled$2110, Incomer 1 - Uncontrolled$2112, Incomer 2 - Uncontrolled$2111, Oven &amp; Kitchen Appliances$2108</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Heat Pump$2092, Hot Water - Controlled$2094, Incomer - Uncontrolled$2093, Kitchen$2089, Laundry &amp; 2nd Fridge Freezer$2090, Oven &amp; Hob$2091</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Heat Pump$2758, Hob &amp; Kitchen Appliances$2759, Hot Water - Controlled$2761, Incomer 1 - Uncontrolled $2763, Incomer 1 - Uncontrolled$2757, Incomer 2 - Uncontrolled $2762, Oven$2760</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Heat Pump$2758, Hob &amp; Kitchen Appliances$2759, Hot Water - Controlled$2761, Incomer 1 - Uncontrolled $2763, Incomer 2 - Uncontrolled $2762, Oven$2760</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Heat Pump$4124, Hot Water - Uncontrolled$4125, Incomer - Uncontrolled$4126, Kitchen Appliances$4121, Laundry, Garage Fridge Freezer$4122, Lighting$4123</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">134</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Heat Pump$4130, Hot Water - Uncontrolled$4131, Incomer - All$4132, Kitchen Appliances$4127, Laundry &amp; Freezer$4128, Lighting (inc heat lamps)$4129</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">45</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Heat Pump$4134, Hot Water - Controlled$4135, Incomer -Uncontrolled$4136, Kitchen Appliances$4137, Laundry &amp; Fridge Freezer$4138, Lighting$4133</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">507</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Heat Pump$4150, Hot Water - Uncontrolled$4147, Incomer - All$4148, Kitchen Appliances$4145, Lighting$4149, Washing Machine$4146</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">458</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Heat Pump$4154, Hot Water - Controlled$4155, Incomer - Uncontrolled$4156, Kitchen Appliances$4151, Laundry $4152, Lighting$4153</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">508</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Heat Pump$4160, Hot Water - Controlled$4158, Incomer - Uncontrolled$4157, Kitchen Appliances$4161, Laundry &amp; Garage Fridge$4162, Lighting$4159</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Heat Pump$4175, Hot Water - Controlled$4178, Incomer - Uncontrolled$4177, Kitchen, Dining &amp; Office$4179, Laundry, Lounge, Garage, Bed$4180, Lighting$4176</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">402</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Heat Pump$4190, Incomer - All$4192, Kitchen Appliances$4187, Laundry$4188, Lighting$4189, Oven$4191</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">499</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Heat Pump$4196, Hot Water - Controlled$4198, Incomer - All$4193, Kitchen Appliances$4195, Laundry$4194, Lighting$4197</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Heat Pump$4204, Hot Water - Controlled$4200, Incomer - All$4199, Kitchen Appliances$4201, Laundry$4202, Lighting$4203</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">508</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Heat Pump$4211, Incomer - All$4213, Kitchen Appliances$4210, Laundry, Garage &amp; Guest Bed$4215, Lighting$4212, Oven$4214</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">4</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Heat Pump$4219, Incomer - All$4221, Kitchen Appliances$4216, Laundry$4217, Lighting$4218, PV &amp; Garage$4220</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Heat Pump$4223, Hot Water - Uncontrolled$4224, Incomer - All$4225, Kitchen Appliances$4226, Laundry &amp; Garage Freezer$4227, Lighting$4222</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Heat Pumps (2x) &amp; Power$4232, Heat Pumps (2x) &amp; Power$4399, Hot Water - Controlled$4231, Hot Water - Controlled$4400, Incomer - Uncontrolled$4230, Incomer - Uncontrolled$4401, Incomer Voltage$4405, Kitchen &amp; Bedrooms$4229, Kitchen &amp; Bedrooms$4402, Laundry &amp; Bedrooms$4228, Laundry &amp; Bedrooms$4403, Lighting$4233, Lighting$4404</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">411</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Hob$3954, Hot Water$3952, Incomer 1$3956, Incomer 2$3955, Laundry &amp; Kitchen Appliances$3951, Oven$3953</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Hot Water (2 elements)$4247, Incomer - Uncontrolled$4248, Kitchen Appliances$4244, Lighting &amp; 2 Towel Rail$4245, Oven$4246</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">384</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Hot Water - Controlled (HEMS)$2081, Incomer - Uncontrolled$2082, Kitchen, Laundry &amp; Ventilation$2084, Oven$2085, PV &amp; Storage$2083, Spa (HEMS)$2080</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">508</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Hot Water - Controlled$2102, Incomer - Uncontrolled$2101, Kitchen$2104, Laundry, Fridge &amp; Freezer$2105, Oven &amp; Hob$2103, PV$2106</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">508</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Hot Water - Controlled$2129, Incomer 1 - Uncontrolled$2128, Incomer 2 - Uncontrolled$2130, Kitchen Appliances &amp; Ventilati$2131, Laundry &amp; Hob$2133, Oven$2132</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Hot Water - Controlled$2236, Incomer - Uncontrolled$2237, Kitchen &amp; Laundry$2234, Lighting$2232, Oven$2235, Ventilation &amp; Lounge Power$2233</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">371</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Hot Water - Controlled$2248, Incomer - Uncontrolled$2249, Kitchen$2246, Laundry, Downstairs &amp; Lounge$2245, Lighting$2244, Oven &amp; Hob$2247</td>
<td align="right">206</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Hot Water - Controlled$2719, Incomer 1 - Uncont inc Stove$2718, Incomer 2 - Uncont inc Oven$2717, Kitchen Appliances$2715, Laundry &amp; Microwave$2720, Power Outlets$2716</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">329</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Hot Water - Controlled$4144, Incomer - Uncontrolled$4143, Kitchen Appliances &amp; Heat Pump$4140, Laundry &amp; Teenagers Bedroom$4139, Lighting$4142, Oven, Hob &amp; Microwave$4141</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">507</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Hot Water - Controlled$4238, Incomer - All$4239, Kitchen Appliances$4234, Laundry &amp; Kitchen$4235, Lighting$4236, Oven &amp; Hobb$4237</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Incomer 1 - All$2703, Incomer 2 - All$2704, Kitchen Appliances$2706, Laundry, Sauna &amp; 2nd Fridge$2707, Oven$2705, Spa$2708</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">414</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td>Incomer 1 - Hot Water - Cont$2626, Incomer 2 - Uncontrolled$2625, Incomer 3 - Uncontrolled$2627, Kitchen Appliances &amp; Lounge$2630, Laundry, Fridge &amp; Microwave$2628, Oven$2629</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td>Incomer 1 - Uncontrolled$2726, Incomer 2 - Uncontrolled$2725, Kitchen Appliances &amp; Laundry$2722, Microwave$2721, Oven$2724, Workshop$2723</td>
<td align="right">0</td>
<td align="right">206</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>Errors are easy to spot in the following plot where a hhID spans 2 or more circuit labels.</p>
<p><img src="processGridSpy1minData_files/figure-html/plotCircuitLabelIssuesAsTile-1.png" /><!-- --></p>
<pre><code>## Saving 7 x 8 in image</code></pre>
<p>The following table provides more detail to aid error checking. Check for:</p>
<ul>
<li>2+ adjacent rows which have exactly the same circuit labels but different hh_ids. This implies some data from one household has been saved in the wrong folder;</li>
<li>2+ adjacent rows which have different circuit labels but identical hh_ids. This could imply the same thing but is more likely to be errors/changes to the circuit labelling.</li>
</ul>
<p>If the above plot and this table flag a lot of errors then some re-naming of the circuit labels (column names) may be necessary.</p>
<blockquote>
<p>NB: As before, the table is only legible in the html version of this report because latex does a very bad job of wrapping table cell text. A version is saved in /Volumes/hum-csafe/Research Projects/GREEN Grid/Clean_data/safe/gridSpy/1min/circuitLabelMetaDataCheckTable.csv for viewing in e.g. xl.</p>
</blockquote>
<table>
<caption>Circuit labels by household with addiitonal meta-data</caption>
<thead>
<tr class="header">
<th align="left">circuitLabels</th>
<th align="left">hhID</th>
<th align="left">sample</th>
<th align="right">nFiles</th>
<th align="left">minObsDate</th>
<th align="left">maxObsDate</th>
<th align="left">minFileDate</th>
<th align="left">maxFileDate</th>
<th align="right">nObs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bed 2, 2nd Fridge$2828, Heat Pump$2826, Hot Water - Controlled$2825, Incomer - Uncontrolled$2824, Kitchen, Laundry &amp; Beds 1&amp;3$2829, Oven &amp; Oven Wall Appliances$2827</td>
<td align="left">rf_27</td>
<td align="left">Powerco</td>
<td align="right">3</td>
<td align="left">2014-07-27</td>
<td align="left">2016-05-13</td>
<td align="left">2016-05-25</td>
<td align="left">2016-09-21</td>
<td align="right">1419097</td>
</tr>
<tr class="even">
<td align="left">Bedroom &amp; Lounge Heat Pumps$2741, Incomer 1 - All$2738, Incomer 2 - All$2737, Kitchen Appliances$2735, Laundry$2734, Oven$2736, PV 1$2739, PV 2$2733, Theatre Heat Pump$2740</td>
<td align="left">rf_19</td>
<td align="left">Powerco</td>
<td align="right">508</td>
<td align="left">2014-07-14</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">4173266</td>
</tr>
<tr class="odd">
<td align="left">Bedrooms &amp; Lounge$2602, Heat Pump$2598, Incomer - All$2599, Kitchen Appliances$2601, Laundry &amp; Garage$2597, Oven$2600</td>
<td align="left">rf_10</td>
<td align="left">Powerco</td>
<td align="right">358</td>
<td align="left">2014-07-08</td>
<td align="left">2018-03-29</td>
<td align="left">2016-05-25</td>
<td align="left">2018-03-30</td>
<td align="right">3734792</td>
</tr>
<tr class="even">
<td align="left">Downstairs (inc 1 Heat Pump)$2212, Hot Water - Controlled$2208, Incomer - Uncontrolled$2209, Kitchen &amp; Laundry$2213, Oven &amp; Hob$2210, Upstairs Heat Pumps$2211</td>
<td align="left">rf_13</td>
<td align="left">Powerco</td>
<td align="right">440</td>
<td align="left">2014-06-05</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">3896353</td>
</tr>
<tr class="odd">
<td align="left">Fridge$2752, Heat Pump &amp; Washing Machine$2750, Incomer - All$2748, Kitchen Appliances &amp; Garage$2753, Lower Bedrooms &amp; Bathrooms$2751, Oven$2749</td>
<td align="left">rf_21</td>
<td align="left">Powerco</td>
<td align="right">4</td>
<td align="left">2014-07-14</td>
<td align="left">2016-07-01</td>
<td align="left">2016-05-25</td>
<td align="left">2016-10-12</td>
<td align="right">1972512</td>
</tr>
<tr class="even">
<td align="left">Hallway &amp; Washing Machine$2683, Hot Water - Controlled$2679, Incomer 1 - Uncont inc Oven$2681, Incomer 2 - Uncont inc Stove$2680, Kitchen Appliances &amp; Bedrooms$2684, Microwave &amp; Breadmaker$2682</td>
<td align="left">rf_16</td>
<td align="left">Powerco</td>
<td align="right">1</td>
<td align="left">2014-07-09</td>
<td align="left">2015-03-25</td>
<td align="left">2016-09-20</td>
<td align="left">2016-09-20</td>
<td align="right">373523</td>
</tr>
<tr class="odd">
<td align="left">Heat Pump &amp; 2 x Bathroom Heat$4171, Incomer - All$4170, Kitchen Power &amp; Heat, Lounge$4174, Laundry, Garage &amp; 2 Bedrooms$4173, Lighting$4172, Wall Oven$4169</td>
<td align="left">rf_47</td>
<td align="left">Unison</td>
<td align="right">3</td>
<td align="left">2015-03-24</td>
<td align="left">2016-05-08</td>
<td align="left">2016-05-25</td>
<td align="left">2016-09-20</td>
<td align="right">1180942</td>
</tr>
<tr class="even">
<td align="left">Heat Pump &amp; Bedroom 2$2731, Incomer 1 - Uncont - Inc Hob$2729, Incomer 2 - Uncont - Inc Oven$2730, Kitchen Appliances$2727, Laundry$2732, Lounge, Dining &amp; Bedrooms$2728</td>
<td align="left">rf_09</td>
<td align="left">Powerco</td>
<td align="right">2</td>
<td align="left">2014-07-13</td>
<td align="left">2015-07-16</td>
<td align="left">2016-09-21</td>
<td align="left">2016-09-21</td>
<td align="right">529363</td>
</tr>
<tr class="odd">
<td align="left">Heat Pump &amp; Kitchen Appliances$4186, Hot Water - Controlled$4184, Incomer - Uncontrolled$4181, Laundry$4185, Lighting$4183, Oven$4182</td>
<td align="left">rf_29</td>
<td align="left">Unison</td>
<td align="right">505</td>
<td align="left">2015-03-25</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">3288151</td>
</tr>
<tr class="even">
<td align="left">Heat Pump &amp; Lounge$2590, Hob$2589, Hot Water Cpbd Heater- Cont$2586, Incomer - Uncontrolled$2585, Kitchen Appliances &amp; Laundry$2588, Spa - Uncontrolled$2587</td>
<td align="left">rf_11</td>
<td align="left">Powerco</td>
<td align="right">508</td>
<td align="left">2014-07-07</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">4189933</td>
</tr>
<tr class="odd">
<td align="left">Heat Pump &amp; Misc$2107, Hob$2109, Hot Water - Controlled$2110, Incomer 1 - Uncontrolled$2112, Incomer 2 - Uncontrolled$2111, Oven &amp; Kitchen Appliances$2108</td>
<td align="left">rf_20</td>
<td align="left">Powerco</td>
<td align="right">2</td>
<td align="left">2014-05-28</td>
<td align="left">2015-06-11</td>
<td align="left">2016-09-21</td>
<td align="left">2016-09-21</td>
<td align="right">545138</td>
</tr>
<tr class="even">
<td align="left">Heat Pump (x2) &amp; Lounge Power$4166, Hot Water - Controlled$4167, Incomer - Uncontrolled$4168, Kitchen Appliances$4163, Laundry$4164, Lighting$4165</td>
<td align="left">rf_40</td>
<td align="left">Unison</td>
<td align="right">2</td>
<td align="left">2015-03-24</td>
<td align="left">2015-11-22</td>
<td align="left">2016-06-08</td>
<td align="left">2016-09-20</td>
<td align="right">349528</td>
</tr>
<tr class="odd">
<td align="left">Heat Pump$2092, Hot Water - Controlled$2094, Incomer - Uncontrolled$2093, Kitchen$2089, Laundry &amp; 2nd Fridge Freezer$2090, Oven &amp; Hob$2091</td>
<td align="left">rf_08</td>
<td align="left">Powerco</td>
<td align="right">5</td>
<td align="left">2014-05-28</td>
<td align="left">2017-05-15</td>
<td align="left">2016-05-25</td>
<td align="left">2017-11-21</td>
<td align="right">2536195</td>
</tr>
<tr class="even">
<td align="left">Heat Pump$2758, Hob &amp; Kitchen Appliances$2759, Hot Water - Controlled$2761, Incomer 1 - Uncontrolled $2763, Incomer 1 - Uncontrolled$2757, Incomer 2 - Uncontrolled $2762, Oven$2760</td>
<td align="left">rf_25</td>
<td align="left">Powerco</td>
<td align="right">1</td>
<td align="left">2015-05-24</td>
<td align="left">2016-05-25</td>
<td align="left">2016-06-08</td>
<td align="left">2016-06-08</td>
<td align="right">507847</td>
</tr>
<tr class="odd">
<td align="left">Heat Pump$2758, Hob &amp; Kitchen Appliances$2759, Hot Water - Controlled$2761, Incomer 1 - Uncontrolled $2763, Incomer 2 - Uncontrolled $2762, Oven$2760</td>
<td align="left">rf_25</td>
<td align="left">Powerco</td>
<td align="right">2</td>
<td align="left">2016-05-25</td>
<td align="left">2016-10-22</td>
<td align="left">2016-10-25</td>
<td align="left">2017-11-21</td>
<td align="right">213418</td>
</tr>
<tr class="even">
<td align="left">Heat Pump$4124, Hot Water - Uncontrolled$4125, Incomer - Uncontrolled$4126, Kitchen Appliances$4121, Laundry, Garage Fridge Freezer$4122, Lighting$4123</td>
<td align="left">rf_35</td>
<td align="left">Unison</td>
<td align="right">134</td>
<td align="left">2015-03-22</td>
<td align="left">2017-05-17</td>
<td align="left">2016-05-25</td>
<td align="left">2017-11-21</td>
<td align="right">1494089</td>
</tr>
<tr class="odd">
<td align="left">Heat Pump$4130, Hot Water - Uncontrolled$4131, Incomer - All$4132, Kitchen Appliances$4127, Laundry &amp; Freezer$4128, Lighting (inc heat lamps)$4129</td>
<td align="left">rf_42</td>
<td align="left">Unison</td>
<td align="right">45</td>
<td align="left">2015-03-23</td>
<td align="left">2017-02-18</td>
<td align="left">2016-06-08</td>
<td align="left">2017-11-21</td>
<td align="right">1099072</td>
</tr>
<tr class="even">
<td align="left">Heat Pump$4134, Hot Water - Controlled$4135, Incomer -Uncontrolled$4136, Kitchen Appliances$4137, Laundry &amp; Fridge Freezer$4138, Lighting$4133</td>
<td align="left">rf_37</td>
<td align="left">Unison</td>
<td align="right">507</td>
<td align="left">2015-03-23</td>
<td align="left">2018-05-30</td>
<td align="left">2016-06-08</td>
<td align="left">2018-05-30</td>
<td align="right">2849674</td>
</tr>
<tr class="odd">
<td align="left">Heat Pump$4150, Hot Water - Uncontrolled$4147, Incomer - All$4148, Kitchen Appliances$4145, Lighting$4149, Washing Machine$4146</td>
<td align="left">rf_36</td>
<td align="left">Unison</td>
<td align="right">458</td>
<td align="left">2015-03-23</td>
<td align="left">2018-05-30</td>
<td align="left">2016-06-08</td>
<td align="left">2018-05-30</td>
<td align="right">2675600</td>
</tr>
<tr class="even">
<td align="left">Heat Pump$4154, Hot Water - Controlled$4155, Incomer - Uncontrolled$4156, Kitchen Appliances$4151, Laundry $4152, Lighting$4153</td>
<td align="left">rf_44</td>
<td align="left">Unison</td>
<td align="right">508</td>
<td align="left">2015-03-24</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">3464121</td>
</tr>
<tr class="odd">
<td align="left">Heat Pump$4160, Hot Water - Controlled$4158, Incomer - Uncontrolled$4157, Kitchen Appliances$4161, Laundry &amp; Garage Fridge$4162, Lighting$4159</td>
<td align="left">rf_45</td>
<td align="left">Unison</td>
<td align="right">4</td>
<td align="left">2015-03-24</td>
<td align="left">2016-10-15</td>
<td align="left">2016-06-08</td>
<td align="left">2017-11-21</td>
<td align="right">821472</td>
</tr>
<tr class="even">
<td align="left">Heat Pump$4175, Hot Water - Controlled$4178, Incomer - Uncontrolled$4177, Kitchen, Dining &amp; Office$4179, Laundry, Lounge, Garage, Bed$4180, Lighting$4176</td>
<td align="left">rf_38</td>
<td align="left">Unison</td>
<td align="right">402</td>
<td align="left">2015-03-24</td>
<td align="left">2017-08-22</td>
<td align="left">2016-06-08</td>
<td align="left">2017-11-21</td>
<td align="right">2913338</td>
</tr>
<tr class="odd">
<td align="left">Heat Pump$4190, Incomer - All$4192, Kitchen Appliances$4187, Laundry$4188, Lighting$4189, Oven$4191</td>
<td align="left">rf_41</td>
<td align="left">Unison</td>
<td align="right">499</td>
<td align="left">2015-03-25</td>
<td align="left">2018-05-30</td>
<td align="left">2016-06-08</td>
<td align="left">2018-05-30</td>
<td align="right">2441615</td>
</tr>
<tr class="even">
<td align="left">Heat Pump$4196, Hot Water - Controlled$4198, Incomer - All$4193, Kitchen Appliances$4195, Laundry$4194, Lighting$4197</td>
<td align="left">rf_32</td>
<td align="left">Unison</td>
<td align="right">2</td>
<td align="left">2015-03-25</td>
<td align="left">2016-04-05</td>
<td align="left">2016-06-08</td>
<td align="left">2016-09-20</td>
<td align="right">542484</td>
</tr>
<tr class="odd">
<td align="left">Heat Pump$4204, Hot Water - Controlled$4200, Incomer - All$4199, Kitchen Appliances$4201, Laundry$4202, Lighting$4203</td>
<td align="left">rf_31</td>
<td align="left">Unison</td>
<td align="right">508</td>
<td align="left">2015-03-25</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">3459721</td>
</tr>
<tr class="even">
<td align="left">Heat Pump$4211, Incomer - All$4213, Kitchen Appliances$4210, Laundry, Garage &amp; Guest Bed$4215, Lighting$4212, Oven$4214</td>
<td align="left">rf_43</td>
<td align="left">Unison</td>
<td align="right">4</td>
<td align="left">2015-03-26</td>
<td align="left">2015-10-18</td>
<td align="left">2016-05-25</td>
<td align="left">2016-09-28</td>
<td align="right">890700</td>
</tr>
<tr class="odd">
<td align="left">Heat Pump$4219, Incomer - All$4221, Kitchen Appliances$4216, Laundry$4217, Lighting$4218, PV &amp; Garage$4220</td>
<td align="left">rf_28</td>
<td align="left">Unison</td>
<td align="right">2</td>
<td align="left">2015-03-26</td>
<td align="left">2015-05-26</td>
<td align="left">2016-06-08</td>
<td align="left">2016-09-19</td>
<td align="right">87417</td>
</tr>
<tr class="even">
<td align="left">Heat Pump$4223, Hot Water - Uncontrolled$4224, Incomer - All$4225, Kitchen Appliances$4226, Laundry &amp; Garage Freezer$4227, Lighting$4222</td>
<td align="left">rf_34</td>
<td align="left">Unison</td>
<td align="right">7</td>
<td align="left">2014-11-03</td>
<td align="left">2016-08-24</td>
<td align="left">2016-05-25</td>
<td align="left">2016-10-13</td>
<td align="right">2066074</td>
</tr>
<tr class="odd">
<td align="left">Heat Pumps (2x) &amp; Power$4232, Heat Pumps (2x) &amp; Power$4399, Hot Water - Controlled$4231, Hot Water - Controlled$4400, Incomer - Uncontrolled$4230, Incomer - Uncontrolled$4401, Incomer Voltage$4405, Kitchen &amp; Bedrooms$4229, Kitchen &amp; Bedrooms$4402, Laundry &amp; Bedrooms$4228, Laundry &amp; Bedrooms$4403, Lighting$4233, Lighting$4404</td>
<td align="left">rf_46</td>
<td align="left">Unison</td>
<td align="right">411</td>
<td align="left">2015-03-26</td>
<td align="left">2018-02-19</td>
<td align="left">2016-06-08</td>
<td align="left">2018-02-21</td>
<td align="right">2529107</td>
</tr>
<tr class="even">
<td align="left">Hob$3954, Hot Water$3952, Incomer 1$3956, Incomer 2$3955, Laundry &amp; Kitchen Appliances$3951, Oven$3953</td>
<td align="left">rf_15</td>
<td align="left">Powerco</td>
<td align="right">2</td>
<td align="left">2015-01-14</td>
<td align="left">2016-04-18</td>
<td align="left">2016-09-21</td>
<td align="left">2016-09-21</td>
<td align="right">395011</td>
</tr>
<tr class="odd">
<td align="left">Hot Water (2 elements)$4247, Incomer - Uncontrolled$4248, Kitchen Appliances$4244, Lighting &amp; 2 Towel Rail$4245, Oven$4246</td>
<td align="left">rf_39</td>
<td align="left">Unison</td>
<td align="right">384</td>
<td align="left">2015-03-27</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">3014770</td>
</tr>
<tr class="even">
<td align="left">Hot Water - Controlled (HEMS)$2081, Incomer - Uncontrolled$2082, Kitchen, Laundry &amp; Ventilation$2084, Oven$2085, PV &amp; Storage$2083, Spa (HEMS)$2080</td>
<td align="left">rf_23</td>
<td align="left">Powerco</td>
<td align="right">508</td>
<td align="left">2014-05-25</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">4253222</td>
</tr>
<tr class="odd">
<td align="left">Hot Water - Controlled$2102, Incomer - Uncontrolled$2101, Kitchen$2104, Laundry, Fridge &amp; Freezer$2105, Oven &amp; Hob$2103, PV$2106</td>
<td align="left">rf_24</td>
<td align="left">Powerco</td>
<td align="right">508</td>
<td align="left">2014-05-28</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">4203991</td>
</tr>
<tr class="even">
<td align="left">Hot Water - Controlled$2129, Incomer 1 - Uncontrolled$2128, Incomer 2 - Uncontrolled$2130, Kitchen Appliances &amp; Ventilati$2131, Laundry &amp; Hob$2133, Oven$2132</td>
<td align="left">rf_18</td>
<td align="left">Powerco</td>
<td align="right">2</td>
<td align="left">2014-05-29</td>
<td align="left">2015-06-11</td>
<td align="left">2016-09-21</td>
<td align="left">2016-09-21</td>
<td align="right">543098</td>
</tr>
<tr class="odd">
<td align="left">Hot Water - Controlled$2236, Incomer - Uncontrolled$2237, Kitchen &amp; Laundry$2234, Lighting$2232, Oven$2235, Ventilation &amp; Lounge Power$2233</td>
<td align="left">rf_22</td>
<td align="left">Powerco</td>
<td align="right">371</td>
<td align="left">2014-06-05</td>
<td align="left">2018-01-14</td>
<td align="left">2016-05-25</td>
<td align="left">2018-01-16</td>
<td align="right">3837181</td>
</tr>
<tr class="even">
<td align="left">Hot Water - Controlled$2248, Incomer - Uncontrolled$2249, Kitchen$2246, Laundry, Downstairs &amp; Lounge$2245, Lighting$2244, Oven &amp; Hob$2247</td>
<td align="left">rf_06</td>
<td align="left">Powerco</td>
<td align="right">206</td>
<td align="left">2014-06-08</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">2964716</td>
</tr>
<tr class="odd">
<td align="left">Hot Water - Controlled$2719, Incomer 1 - Uncont inc Stove$2718, Incomer 2 - Uncont inc Oven$2717, Kitchen Appliances$2715, Laundry &amp; Microwave$2720, Power Outlets$2716</td>
<td align="left">rf_14</td>
<td align="left">Powerco</td>
<td align="right">329</td>
<td align="left">2014-07-13</td>
<td align="left">2017-12-30</td>
<td align="left">2016-06-08</td>
<td align="left">2017-12-31</td>
<td align="right">2654180</td>
</tr>
<tr class="even">
<td align="left">Hot Water - Controlled$4144, Incomer - Uncontrolled$4143, Kitchen Appliances &amp; Heat Pump$4140, Laundry &amp; Teenagers Bedroom$4139, Lighting$4142, Oven, Hob &amp; Microwave$4141</td>
<td align="left">rf_33</td>
<td align="left">Unison</td>
<td align="right">507</td>
<td align="left">2015-03-23</td>
<td align="left">2018-05-30</td>
<td align="left">2016-06-08</td>
<td align="left">2018-05-30</td>
<td align="right">2749942</td>
</tr>
<tr class="odd">
<td align="left">Hot Water - Controlled$4238, Incomer - All$4239, Kitchen Appliances$4234, Laundry &amp; Kitchen$4235, Lighting$4236, Oven &amp; Hobb$4237</td>
<td align="left">rf_30</td>
<td align="left">Unison</td>
<td align="right">5</td>
<td align="left">2015-03-27</td>
<td align="left">2016-09-29</td>
<td align="left">2016-05-25</td>
<td align="left">2016-10-13</td>
<td align="right">1454037</td>
</tr>
<tr class="even">
<td align="left">Incomer 1 - All$2703, Incomer 2 - All$2704, Kitchen Appliances$2706, Laundry, Sauna &amp; 2nd Fridge$2707, Oven$2705, Spa$2708</td>
<td align="left">rf_26</td>
<td align="left">Powerco</td>
<td align="right">414</td>
<td align="left">2014-07-10</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">3239136</td>
</tr>
<tr class="odd">
<td align="left">Incomer 1 - Hot Water - Cont$2626, Incomer 2 - Uncontrolled$2625, Incomer 3 - Uncontrolled$2627, Kitchen Appliances &amp; Lounge$2630, Laundry, Fridge &amp; Microwave$2628, Oven$2629</td>
<td align="left">rf_12</td>
<td align="left">Powerco</td>
<td align="right">2</td>
<td align="left">2014-07-08</td>
<td align="left">2015-06-02</td>
<td align="left">2016-09-21</td>
<td align="left">2016-09-21</td>
<td align="right">410063</td>
</tr>
<tr class="even">
<td align="left">Incomer 1 - Uncontrolled$2726, Incomer 2 - Uncontrolled$2725, Kitchen Appliances &amp; Laundry$2722, Microwave$2721, Oven$2724, Workshop$2723</td>
<td align="left">rf_07</td>
<td align="left">Powerco</td>
<td align="right">206</td>
<td align="left">2014-07-13</td>
<td align="left">2018-05-30</td>
<td align="left">2016-05-25</td>
<td align="left">2018-05-30</td>
<td align="right">3216449</td>
</tr>
</tbody>
</table>
<p>Things to note:</p>
<ul>
<li>rf_25 has an aditional unexpected “Incomer 1 - Uncontrolled$2757” circuit in some files but it’s value is always NA so we have not ‘corrected’ this.</li>
</ul>
</div>
<div id="observations" class="section level2">
<h2><span class="header-section-number">6.2</span> Observations</h2>
<p>The following plots show the number of observations per day per household. In theory we should not see:</p>
<ul>
<li>dates before 2014 or in to the future. These may indicate:
<ul>
<li>date conversion errors;</li>
</ul></li>
<li>more than 1440 observations per day. These may indicate:
<ul>
<li>duplicate time stamps - i.e. they have the same time stamps but different power (W) values or different circuit labels;</li>
<li>observations from files that are in the ‘wrong’ rf_XX folder and so are included in the ‘wrong’ household as ‘duplicate’ time stamps.</li>
</ul></li>
</ul>
<p>If present both of the latter may have been implied by the table above and would have evaded the de-duplication filter which simply checks each complete row against all others within it’s consolidated household dataset (a <em>within household absolute duplicate</em> check).</p>
<pre><code>## Warning: Removed 3 rows containing missing values (geom_tile).</code></pre>
<p><img src="processGridSpy1minData_files/figure-html/loadedFilesObsPlots-1.png" /><!-- --></p>
<pre><code>## Saving 7 x 5 in image</code></pre>
<pre><code>## Warning: Removed 3 rows containing missing values (geom_tile).</code></pre>
<pre><code>## Warning: Removed 3 rows containing missing values (geom_point).</code></pre>
<p><img src="processGridSpy1minData_files/figure-html/plot%20n%20obs%20per%20hh%20id%20as%20dots-1.png" /><!-- --></p>
<pre><code>## Saving 7 x 5 in image</code></pre>
<pre><code>## Warning: Removed 3 rows containing missing values (geom_point).</code></pre>
<p>The following table shows the min/max observations per day and min/max dates for each household. As above, we should not see:</p>
<ul>
<li>dates before 2014 or in to the future (indicates date conversion errors)</li>
<li>more than 1440 observations per day (indicates potentially duplicate observations)</li>
<li>non-integer counts of circuits as it suggests some column errors</li>
</ul>
<p>We should also not see NA in any row (indicates date conversion errors).</p>
<p>If we do see any of these then we still have data cleaning work to do!</p>
<table>
<caption>Summary observation stats by hhID (sorted by date last heard from)</caption>
<thead>
<tr class="header">
<th align="left">hhID</th>
<th align="left">sample</th>
<th align="right">minObs</th>
<th align="right">maxObs</th>
<th align="right">meanNDataColumns</th>
<th align="left">minDate</th>
<th align="left">maxDate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">rf_16</td>
<td align="left">Powerco</td>
<td align="right">720</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-07-09</td>
<td align="left">2015-03-25</td>
</tr>
<tr class="even">
<td align="left">rf_28</td>
<td align="left">Unison</td>
<td align="right">297</td>
<td align="right">1440</td>
<td align="right">6</td>
<td align="left">2015-03-26</td>
<td align="left">2015-05-26</td>
</tr>
<tr class="odd">
<td align="left">rf_12</td>
<td align="left">Powerco</td>
<td align="right">85</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-07-08</td>
<td align="left">2015-06-02</td>
</tr>
<tr class="even">
<td align="left">rf_18</td>
<td align="left">Powerco</td>
<td align="right">157</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-05-29</td>
<td align="left">2015-06-11</td>
</tr>
<tr class="odd">
<td align="left">rf_20</td>
<td align="left">Powerco</td>
<td align="right">98</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-05-28</td>
<td align="left">2015-06-11</td>
</tr>
<tr class="even">
<td align="left">rf_09</td>
<td align="left">Powerco</td>
<td align="right">163</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-07-13</td>
<td align="left">2015-07-16</td>
</tr>
<tr class="odd">
<td align="left">rf_43</td>
<td align="left">Unison</td>
<td align="right">780</td>
<td align="right">1495</td>
<td align="right">6</td>
<td align="left">2015-03-26</td>
<td align="left">2015-10-18</td>
</tr>
<tr class="even">
<td align="left">rf_40</td>
<td align="left">Unison</td>
<td align="right">268</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-24</td>
<td align="left">2015-11-22</td>
</tr>
<tr class="odd">
<td align="left">rf_32</td>
<td align="left">Unison</td>
<td align="right">325</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-25</td>
<td align="left">2016-04-05</td>
</tr>
<tr class="even">
<td align="left">rf_15</td>
<td align="left">Powerco</td>
<td align="right">62</td>
<td align="right">1440</td>
<td align="right">6</td>
<td align="left">2015-01-14</td>
<td align="left">2016-04-18</td>
</tr>
<tr class="odd">
<td align="left">rf_47</td>
<td align="left">Unison</td>
<td align="right">159</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-24</td>
<td align="left">2016-05-08</td>
</tr>
<tr class="even">
<td align="left">rf_27</td>
<td align="left">Powerco</td>
<td align="right">567</td>
<td align="right">1560</td>
<td align="right">6</td>
<td align="left">2014-07-27</td>
<td align="left">2016-05-13</td>
</tr>
<tr class="odd">
<td align="left">rf_21</td>
<td align="left">Powerco</td>
<td align="right">195</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-07-14</td>
<td align="left">2016-07-01</td>
</tr>
<tr class="even">
<td align="left">rf_34</td>
<td align="left">Unison</td>
<td align="right">317</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-11-03</td>
<td align="left">2016-08-24</td>
</tr>
<tr class="odd">
<td align="left">rf_30</td>
<td align="left">Unison</td>
<td align="right">205</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-27</td>
<td align="left">2016-09-29</td>
</tr>
<tr class="even">
<td align="left">rf_45</td>
<td align="left">Unison</td>
<td align="right">69</td>
<td align="right">1499</td>
<td align="right">6</td>
<td align="left">2015-03-24</td>
<td align="left">2016-10-15</td>
</tr>
<tr class="odd">
<td align="left">rf_25</td>
<td align="left">Powerco</td>
<td align="right">45</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-05-24</td>
<td align="left">2016-10-22</td>
</tr>
<tr class="even">
<td align="left">rf_42</td>
<td align="left">Unison</td>
<td align="right">79</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-23</td>
<td align="left">2017-02-18</td>
</tr>
<tr class="odd">
<td align="left">rf_08</td>
<td align="left">Powerco</td>
<td align="right">123</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-05-28</td>
<td align="left">2017-05-15</td>
</tr>
<tr class="even">
<td align="left">rf_35</td>
<td align="left">Unison</td>
<td align="right">50</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-22</td>
<td align="left">2017-05-17</td>
</tr>
<tr class="odd">
<td align="left">rf_38</td>
<td align="left">Unison</td>
<td align="right">398</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-24</td>
<td align="left">2017-08-22</td>
</tr>
<tr class="even">
<td align="left">rf_14</td>
<td align="left">Powerco</td>
<td align="right">120</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-07-13</td>
<td align="left">2017-12-30</td>
</tr>
<tr class="odd">
<td align="left">rf_22</td>
<td align="left">Powerco</td>
<td align="right">6</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-06-05</td>
<td align="left">2018-01-14</td>
</tr>
<tr class="even">
<td align="left">rf_46</td>
<td align="left">Unison</td>
<td align="right">305</td>
<td align="right">1500</td>
<td align="right">13</td>
<td align="left">2015-03-26</td>
<td align="left">2018-02-19</td>
</tr>
<tr class="odd">
<td align="left">rf_10</td>
<td align="left">Powerco</td>
<td align="right">389</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-07-08</td>
<td align="left">2018-03-29</td>
</tr>
<tr class="even">
<td align="left">rf_06</td>
<td align="left">Powerco</td>
<td align="right">243</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-06-08</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_07</td>
<td align="left">Powerco</td>
<td align="right">105</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-07-13</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_11</td>
<td align="left">Powerco</td>
<td align="right">278</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-07-07</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_13</td>
<td align="left">Powerco</td>
<td align="right">456</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-06-05</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_19</td>
<td align="left">Powerco</td>
<td align="right">387</td>
<td align="right">1500</td>
<td align="right">9</td>
<td align="left">2014-07-14</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_23</td>
<td align="left">Powerco</td>
<td align="right">171</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-05-25</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_24</td>
<td align="left">Powerco</td>
<td align="right">571</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2014-05-28</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_26</td>
<td align="left">Powerco</td>
<td align="right">362</td>
<td align="right">2231</td>
<td align="right">6</td>
<td align="left">2014-07-10</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_29</td>
<td align="left">Unison</td>
<td align="right">720</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-25</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_31</td>
<td align="left">Unison</td>
<td align="right">720</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-25</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_33</td>
<td align="left">Unison</td>
<td align="right">369</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-23</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_36</td>
<td align="left">Unison</td>
<td align="right">29</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-23</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_37</td>
<td align="left">Unison</td>
<td align="right">720</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-23</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_39</td>
<td align="left">Unison</td>
<td align="right">163</td>
<td align="right">1823</td>
<td align="right">5</td>
<td align="left">2015-03-27</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_41</td>
<td align="left">Unison</td>
<td align="right">1</td>
<td align="right">1573</td>
<td align="right">6</td>
<td align="left">2015-03-25</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="odd">
<td align="left">rf_44</td>
<td align="left">Unison</td>
<td align="right">720</td>
<td align="right">1500</td>
<td align="right">6</td>
<td align="left">2015-03-24</td>
<td align="left">2018-05-30</td>
</tr>
<tr class="even">
<td align="left">rf_15_old</td>
<td align="left">Powerco</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">rf_17 sn_662</td>
<td align="left">Powerco</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">rf_17_oldNo reused</td>
<td align="left">Powerco</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
<p>Finally we show the total number of households which we think are still sending data.</p>
<pre><code>## Warning: Removed 1 rows containing missing values (position_stack).</code></pre>
<p><img src="processGridSpy1minData_files/figure-html/liveDataHouseholds-1.png" /><!-- --></p>
<pre><code>## Saving 7 x 5 in image</code></pre>
<pre><code>## Warning: Removed 1 rows containing missing values (position_stack).</code></pre>
</div>
</div>
<div id="summary" class="section level1">
<h1><span class="header-section-number">7</span> Summary</h1>
<p>The cleaned data has been saved as gzipped .csv files to /Volumes/hum-csafe/Research Projects/GREEN Grid/Clean_data/safe/gridSpy/1min/ in ‘long’ form so that each file only has 4 columns:</p>
<ul>
<li>hhID: household id</li>
<li>r_dateTime: time of observation</li>
<li>circuit: the circuit label</li>
<li>powerW: power observation (Watts)</li>
</ul>
<p>Each file has data for one household and there should be one file per household.</p>
<p>As an example, here are the first few rows of one of the files:</p>
<table>
<caption>Example data rows</caption>
<thead>
<tr class="header">
<th align="left">hhID</th>
<th align="left">r_dateTime</th>
<th align="left">circuit</th>
<th align="right">powerW</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">rf_01</td>
<td align="left">2014-01-06 03:03:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">45.58</td>
</tr>
<tr class="even">
<td align="left">rf_01</td>
<td align="left">2014-01-06 03:04:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">45.58</td>
</tr>
<tr class="odd">
<td align="left">rf_01</td>
<td align="left">2014-03-07 02:56:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">45.58</td>
</tr>
<tr class="even">
<td align="left">rf_01</td>
<td align="left">2014-03-07 02:57:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">54.13</td>
</tr>
<tr class="odd">
<td align="left">rf_01</td>
<td align="left">2014-03-07 02:58:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">136.26</td>
</tr>
<tr class="even">
<td align="left">rf_01</td>
<td align="left">2014-03-07 02:59:00</td>
<td align="left">Kitchen power$1632</td>
<td align="right">141.96</td>
</tr>
</tbody>
</table>
<p>This format makes it much easier to do future data extraction in R as we can select by date and circuit label as we load. It also means we can load a lot of data in memory without breaking R’s memory limits as R likes ‘long’ rather than wide data.</p>
</div>
<div id="runtime" class="section level1">
<h1><span class="header-section-number">8</span> Runtime</h1>
<p>Analysis completed in 34.24 seconds ( 0.57 minutes) using <a href="https://cran.r-project.org/package=knitr">knitr</a> in <a href="http://www.rstudio.com">RStudio</a> with R version 3.5.0 (2018-04-23) running on x86_64-apple-darwin15.6.0.</p>
<p>The time taken will have depended on:</p>
<blockquote>
<p>Full run using all data from /Volumes/hum-csafe/Research Projects/GREEN Grid/_RAW DATA/GridSpyData/</p>
</blockquote>
<blockquote>
<p>refreshData = 0 so re-using previous output. Should be relatively quick.</p>
</blockquote>
</div>
<div id="r-environment" class="section level1">
<h1><span class="header-section-number">9</span> R environment</h1>
<p>R packages used:</p>
<ul>
<li>base R - for the basics <span class="citation">(R Core Team 2016)</span></li>
<li>data.table - for fast (big) data handling <span class="citation">(Dowle et al. 2015)</span></li>
<li>lubridate - date manipulation <span class="citation">(Grolemund and Wickham 2011)</span></li>
<li>ggplot2 - for slick graphics <span class="citation">(Wickham 2009)</span></li>
<li>readr - for csv reading/writing <span class="citation">(Wickham, Hester, and Francois 2016)</span></li>
<li>dplyr - for select and contains <span class="citation">(Wickham and Francois 2016)</span></li>
<li>progress - for progress bars <span class="citation">(Csárdi and FitzJohn 2016)</span></li>
<li>knitr - to create this document &amp; neat tables <span class="citation">(Xie 2016)</span></li>
<li>kableExtra - for extra neat tables <span class="citation">(Zhu 2018)</span></li>
<li>nzGREENGrid - for local NZ GREEN Grid project utilities</li>
</ul>
<p>Session info:</p>
<pre><code>## R version 3.5.0 (2018-04-23)
## Platform: x86_64-apple-darwin15.6.0 (64-bit)
## Running under: macOS High Sierra 10.13.4
## 
## Matrix products: default
## BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
## LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
## 
## locale:
## [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] knitr_1.20        readr_1.1.1       ggplot2_2.2.1     data.table_1.11.2
## [5] nzGREENGrid_0.1.0
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_0.12.17      cellranger_1.1.0  highr_0.6        
##  [4] pillar_1.2.2      compiler_3.5.0    plyr_1.8.4       
##  [7] bindr_0.1.1       prettyunits_1.0.2 tools_3.5.0      
## [10] progress_1.1.2    digest_0.6.15     lubridate_1.7.4  
## [13] evaluate_0.10.1   tibble_1.4.2      gtable_0.2.0     
## [16] pkgconfig_2.0.1   rlang_0.2.0       yaml_2.1.19      
## [19] bindrcpp_0.2.2    dplyr_0.7.5       stringr_1.3.1    
## [22] hms_0.4.2         rprojroot_1.3-2   grid_3.5.0       
## [25] tidyselect_0.2.4  glue_1.2.0        R6_2.2.2         
## [28] readxl_1.1.0      rmarkdown_1.9     purrr_0.2.4      
## [31] reshape2_1.4.3    magrittr_1.5      backports_1.1.2  
## [34] scales_0.5.0      htmltools_0.3.6   assertthat_0.2.0 
## [37] colorspace_1.3-2  labeling_0.3      stringi_1.2.2    
## [40] lazyeval_0.2.1    munsell_0.4.3</code></pre>
</div>
<div id="references" class="section level1 unnumbered">
<h1>References</h1>
<div id="refs" class="references">
<div id="ref-progress">
<p>Csárdi, Gábor, and Rich FitzJohn. 2016. <em>Progress: Terminal Progress Bars</em>. <a href="https://CRAN.R-project.org/package=progress" class="uri">https://CRAN.R-project.org/package=progress</a>.</p>
</div>
<div id="ref-data.table">
<p>Dowle, M, A Srinivasan, T Short, S Lianoglou with contributions from R Saporta, and E Antonyan. 2015. <em>Data.table: Extension of Data.frame</em>. <a href="https://CRAN.R-project.org/package=data.table" class="uri">https://CRAN.R-project.org/package=data.table</a>.</p>
</div>
<div id="ref-lubridate">
<p>Grolemund, Garrett, and Hadley Wickham. 2011. “Dates and Times Made Easy with lubridate.” <em>Journal of Statistical Software</em> 40 (3): 1–25. <a href="http://www.jstatsoft.org/v40/i03/" class="uri">http://www.jstatsoft.org/v40/i03/</a>.</p>
</div>
<div id="ref-baseR">
<p>R Core Team. 2016. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing. <a href="https://www.R-project.org/" class="uri">https://www.R-project.org/</a>.</p>
</div>
<div id="ref-ggplot2">
<p>Wickham, Hadley. 2009. <em>Ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York. <a href="http://ggplot2.org" class="uri">http://ggplot2.org</a>.</p>
</div>
<div id="ref-dplyr">
<p>Wickham, Hadley, and Romain Francois. 2016. <em>Dplyr: A Grammar of Data Manipulation</em>. <a href="https://CRAN.R-project.org/package=dplyr" class="uri">https://CRAN.R-project.org/package=dplyr</a>.</p>
</div>
<div id="ref-readr">
<p>Wickham, Hadley, Jim Hester, and Romain Francois. 2016. <em>Readr: Read Tabular Data</em>. <a href="https://CRAN.R-project.org/package=readr" class="uri">https://CRAN.R-project.org/package=readr</a>.</p>
</div>
<div id="ref-knitr">
<p>Xie, Yihui. 2016. <em>Knitr: A General-Purpose Package for Dynamic Report Generation in R</em>. <a href="https://CRAN.R-project.org/package=knitr" class="uri">https://CRAN.R-project.org/package=knitr</a>.</p>
</div>
<div id="ref-kableExtra">
<p>Zhu, Hao. 2018. <em>KableExtra: Construct Complex Table with ’Kable’ and Pipe Syntax</em>. <a href="https://CRAN.R-project.org/package=kableExtra" class="uri">https://CRAN.R-project.org/package=kableExtra</a>.</p>
</div>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
